### ISSUE TITLE
Chapter Idea: Command Line Basics

### ISSUE THREAD

**Issue by adelevie** [vdavez/codingforlawyers#11]
Probably shouldn't be legal/lawyer-specific, but rather than linking to an outside resource, it'd be nice to intro just enough to make the rest of the chapters easier.

**Comment by vdavez** [comment]
:+1: If memory serves, "Learn Python the Hard Way" has a good setup chapter... 
http://learnpythonthehardway.org/book/ex0.html

May want to look there for inspiration...

**Comment by vdavez** [comment]
Going to merge with #23
