### ISSUE TITLE
Fixup regex example

### ISSUE THREAD

**Issue by tmcw** [vdavez/codingforlawyers#14]
So, unfortunately `[1-52]` matches a character class instead of numbers, and [a better solution is kind of convoluted](http://www.regular-expressions.info/numericranges.html). @konklone has far more regex wizard skills than I do and may know of a fix.

**Comment by vdavez** [comment]
Huh. That's a solid point @tmcw. I'll need to rewrite to fix.

**Comment by vdavez** [comment]
Take a look at how I revised it. Thanks again for the catch!

**Comment by vdavez** [comment]
Fixed
