### ISSUE TITLE
License Project

### ISSUE THREAD

**Issue by benbalter** [vdavez/codingforlawyers#16]
The project asks for pull requests, but is licensed as a source-disclosed work ( :copyright: in footer). If you would like contributes, perhaps consider licensing the project under a CC license, such as CC0, CC-BY, or CC-BY-NC?

**Comment by konklone** [comment]
This also implies a `CONTRIBUTING.md` file that informs people of how they're licensing contributions, and, if you want to be rigorous about it, a brief issue or PR where the contributors so far :+1: the licensing of their past contributions.

**Comment by konklone** [comment]
After all, there's nothing more legally rigorous than an emoji thumbs-up.

**Comment by vdavez** [comment]
As per http://tinyletter.com/codingforlawyers/letters/stunned, it will be CC-BY-NC

**Comment by vdavez** [comment]
Thanks again for the issue and the comments!

**Comment by benbalter** [comment]
:sparkling_heart:
