### ISSUE TITLE
Use Headers Semanticly

### ISSUE THREAD

**Issue by benbalter** [vdavez/codingforlawyers#18]
Digging into the markdown, it seems there's a habit of using headers (`#`, `##`, etc.) to make content bold or stand out (e.g., a "next chapter" link), rather than using headings semantically, to provide hierarchy and structure to the content.

In general:
- The site title should be an H1, the largest thing on the page and the overarching title of the content
- The document title (e.g., chapter title) should be an H2, the second least specific thing on the page
- Content should be H3+, with nested headings as appraise
- Headings should not be used for navigational elements

**Comment by vdavez** [comment]
@benbalter did you fix this in #19?

**Comment by benbalter** [comment]
I did not, I can go back and do that now that it's merged. :smile:
