### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by SyntaxColoring** [vdavez/codingforlawyers#2]
I'm a programmer with an interest in typography and web design.  Despite not having any background in law, I really like this website and I'd love to show it to my father (a lawyer) when it's more polished and complete.

Are you looking for contributions?  As someone with no law experience, is there anything I can do to help?

**Comment by adelevie** [comment]
Yes. There is much you can do! cc @vzvenyach

**Comment by vdavez** [comment]
Thanks so much!

There's definitely a lot that can be done. Perhaps the thing for me to do is to actually put together a tentative Table of Contents and see what makes the most sense for contribution? 

Also, to the extent you are familiar with good typography, I would totally welcome any and all CSS improvements. Most lawyers hated math. Not me. But I pretty much failed art class in elementary school and never looked back.

**Comment by vdavez** [comment]
I'm going to merge this comment with the #23 Roadmap
