### ISSUE TITLE
License Confirmation

### ISSUE THREAD

**Issue by vdavez** [vdavez/codingforlawyers#24]
As @konklone notes, I should really get a :+1: from the following: @compleatang, @tmcw, @kirschsubjudice, @underyx, @benbalter, @djfdat, @adelevie, and @snoldak924 for licensing their contributions to this project under a CC-BY-NC-4.0 license.

If you could :+1: that would be excellent!

Meanwhile, wow it's so great to have contributions from all of you.

**Comment by adelevie** [comment]
:thumbsup:

<br />

:dragon_face:

**Comment by snoldak924** [comment]
:thumbsup:

**Comment by ghost** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by compleatang** [comment]
:+1:

**Comment by underyx** [comment]
:+1:

**Comment by benbalter** [comment]
:+1:

**Comment by tmcw** [comment]
Cool with me!

**Comment by djfdat** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by vdavez** [comment]
Woo! Thanks everyone!
