### ISSUE TITLE
chapter idea: hardware and bits

### ISSUE THREAD

**Issue by mlissner** [vdavez/codingforlawyers#6]
This isn't strictly coding, but I think if we're going to educate lawyers about computers we should consider teaching them about hardware basics such as:
- what's the difference between a hard drive, ram and CPU buffers?
- how is everything actually a one or zero?
- how does a CPU work?
- how is a signal sent on a wire?
- encodings as the translation between the letters and binary.
- etc.

Basic thinking is two fold:
1. Lots of people find computers to be magic, and this is the bridge that spans that gap.
2. In any law involving computers, for example copyright, basic understandings like this dictate whether the law was broken (e.g. was a copy made of that MP3?)

I think a chapter like this could be simplified sufficiently to make it work.

**Comment by vdavez** [comment]
I love this idea. I had already planned on a chapter on HTTP. But this is a great suggestion for a chapter. I know _I_ would enjoy reading it.

**Comment by vdavez** [comment]
Going to close and move discussion into #23
