### ISSUE TITLE
Chapter Idea: Distributed Version Control Software -- How to Use Git and Github

### ISSUE THREAD

**Issue by brianwc** [vdavez/codingforlawyers#8]
See title; There are many existing good guides that should probably just be pointed to, but there's still some room to explain the concepts to the legal mind.

**Comment by brianwc** [comment]
Closing as dupe of Issue #5

**Comment by payingattention** [comment]
Explaining programs to a legal mind needs room, and is important.

I encourage you to re-issue as many times as you need log to find logic.

Change freely, so law can learn.
